package com.example.emailmanagerlive.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.emailmanagerlive.data.Configuration;
import com.example.emailmanagerlive.data.Account;

import com.example.emailmanagerlive.data.ConfigurationDao;
import com.example.emailmanagerlive.data.AccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configurationDaoConfig;
    private final DaoConfig accountDaoConfig;

    private final ConfigurationDao configurationDao;
    private final AccountDao accountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configurationDaoConfig = daoConfigMap.get(ConfigurationDao.class).clone();
        configurationDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        configurationDao = new ConfigurationDao(configurationDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);

        registerDao(Configuration.class, configurationDao);
        registerDao(Account.class, accountDao);
    }
    
    public void clear() {
        configurationDaoConfig.clearIdentityScope();
        accountDaoConfig.clearIdentityScope();
    }

    public ConfigurationDao getConfigurationDao() {
        return configurationDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

}
